import {
  Target,
  Calendar,
  Users,
  DollarSign,
  AlertTriangle,
  CircleAlert,
  Circle,
  ChevronRight,
  TrendingDown,
  TrendingUp,
  Clock,
  BarChart3,
  MapPin,
  Map,
  Compass,
  Utensils,
  Music,
  Camera,
  Star,
  Heart,
  ThumbsUp,
  Ticket,
  Bus,
  Car,
  Plane,
  Building2,
  Home,
  GraduationCap,
  BookOpen,
  Lightbulb,
  Zap,
  Shield,
  Lock,
  Globe,
  Phone,
  Mail,
  MessageCircle,
  CheckCircle2,
  XCircle,
  Info,
  HelpCircle,
  Flag,
  Award,
  Trophy,
  Gift,
  ShoppingBag,
  CreditCard,
  Wallet,
  PiggyBank,
  Sunrise,
  Sunset,
  Moon,
  Sun,
  CloudSun,
  Waves,
  Mountain,
  TreePine,
  Sparkles,
  PartyPopper,
  Palette,
  Megaphone,
  Handshake,
  Briefcase,
  FileText,
  LayoutGrid,
  Rocket,
  type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  // General
  target: Target,
  calendar: Calendar,
  users: Users,
  dollar: DollarSign,
  'dollar-sign': DollarSign,
  money: DollarSign,
  warning: AlertTriangle,
  alert: CircleAlert,
  'red-circle': Circle,
  'yellow-circle': Circle,
  circle: Circle,
  'chevron-right': ChevronRight,
  clock: Clock,
  'bar-chart': BarChart3,
  chart: BarChart3,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,

  // Travel & Places
  'map-pin': MapPin,
  location: MapPin,
  pin: MapPin,
  map: Map,
  compass: Compass,
  building: Building2,
  home: Home,
  globe: Globe,
  mountain: Mountain,
  tree: TreePine,
  waves: Waves,

  // Food & Entertainment
  food: Utensils,
  utensils: Utensils,
  restaurant: Utensils,
  dining: Utensils,
  music: Music,
  nightlife: Music,
  camera: Camera,
  photo: Camera,
  ticket: Ticket,
  'party-popper': PartyPopper,
  party: PartyPopper,
  palette: Palette,

  // Transport
  bus: Bus,
  car: Car,
  plane: Plane,
  transport: Bus,

  // People & Social
  star: Star,
  heart: Heart,
  'thumbs-up': ThumbsUp,
  like: ThumbsUp,
  gift: Gift,
  handshake: Handshake,
  megaphone: Megaphone,

  // Business
  briefcase: Briefcase,
  'credit-card': CreditCard,
  wallet: Wallet,
  'piggy-bank': PiggyBank,
  budget: PiggyBank,
  savings: PiggyBank,
  discount: Ticket,
  shopping: ShoppingBag,
  rocket: Rocket,
  award: Award,
  trophy: Trophy,

  // Education
  'graduation-cap': GraduationCap,
  education: GraduationCap,
  book: BookOpen,
  lightbulb: Lightbulb,
  idea: Lightbulb,
  zap: Zap,
  sparkles: Sparkles,

  // Communication
  phone: Phone,
  mail: Mail,
  message: MessageCircle,
  info: Info,
  help: HelpCircle,
  flag: Flag,
  'file-text': FileText,
  layout: LayoutGrid,

  // Status
  check: CheckCircle2,
  success: CheckCircle2,
  error: XCircle,
  shield: Shield,
  lock: Lock,

  // Weather/Time
  sunrise: Sunrise,
  sunset: Sunset,
  moon: Moon,
  sun: Sun,
  'cloud-sun': CloudSun,
};

// All available icon names for the AI prompt
export const AVAILABLE_ICONS = Object.keys(iconMap).join(', ');

export function getIcon(name?: string): LucideIcon | null {
  if (!name) return null;
  return iconMap[name.toLowerCase()] ?? null;
}
